# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/pycqa/flake8
    rev: 7ef0350
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
        exclude: alembic/
        types: [python]

-   repo: https://github.com/pycqa/isort
    rev: c655831
    hooks:
      - id: isort
        types: [python]
